title: Kamirul K.
# logo: /FIGURES/profile_photo.jpg
logo: "/assets/images/profile_photo.jpg" # Path to your logo
description: Welcome to my GitHub Page.

# show_downloads: true
theme: jekyll-theme-minimal


